""" Vocabularies
"""

vocabs = {}

vocabs['themes'] = (
    ('default', 'Default'),
    ('acidification', 'Acidification'),
    ('agriculture', 'Agriculture'),
    ('air', 'Air'),
    ('air_quality', 'Air quality'),
    ('biodiversity', 'Biodiversity change'),
    ('chemicals', 'Chemicals'),
    ('climate', 'Climate change'),
    ('coasts_seas', 'Coasts and seas'),
    ('energy', 'Energy'),
    ('env_information', 'Environmental information'),
    ('env_management', 'Environmental management and practices'),
    ('env_reporting', 'Environmental reporting'),
    ('env_scenarios', 'Environmental scenarios'),
    ('fisheries', 'Fisheries'),
    ('households', 'Households'),
    ('human_health', 'Human health'),
    ('industry', 'Industry'),
    ('natural_resources', 'Natural resources'),
    ('nature', 'Nature'),
    ('noise', 'Noise'),
    ('ozone', 'Ozone depletion'),
    ('policy', 'Policy analysis'),
    ('population', 'Population amd economy'),
    ('regions', 'Regions'),
    ('soil', 'Soil'),
    ('tourism', 'Tourism'),
    ('transport', 'Transport'),
    ('urban', 'Urban environment'),
    ('various', 'Various other issues'),
    ('waste', 'Waste'),
    ('water', 'Water'),
)

vocabs['countries'] = (
    ('default', 'Select your country'),
    ('AND','ANDORRA'),
    ('AUT','AUSTRIA'),
    ('BLR','BELARUS'),
    ('BEL','BELGIUM'),
    ('BIH','BOSNIA AND HERZEGOWINA'),
    ('BGR','BULGARIA'),
    ('HRV','CROATIA (local name: Hrvatska)'),
    ('CYP','CYPRUS'),
    ('CZE','CZECH REPUBLIC'),
    ('DNK','DENMARK'),
    ('SLV','EL SALVADOR'),
    ('EST','ESTONIA'),
    ('FJI','FIJI'),
    ('FIN','FINLAND'),
    ('FRA','FRANCE'),
    ('GEO','GEORGIA'),
    ('DEU','GERMANY'),
    ('GRC','GREECE'),
    ('GRL','GREENLAND'),
    ('HUN','HUNGARY'),
    ('ISL','ICELAND'),
    ('IRL','IRELAND'),
    ('ITA','ITALY'),
    ('LVA','LATVIA'),
    ('LTU','LITHUANIA'),
    ('LUX','LUXEMBOURG'),
    ('MKD','THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA,'),
    ('MLT','MALTA'),
    ('MEX','MEXICO'),
    ('MCO','MONACO'),
    ('NLD','NETHERLANDS'),
    ('NOR','NORWAY'),
    ('POL','POLAND'),
    ('PRT','PORTUGAL'),
    ('ROM','ROMANIA'),
    ('RUS','RUSSIAN FEDERATION'),
    ('SVK','SLOVAKIA (Slovak Republic)'),
    ('SVN','SLOVENIA'),
    ('ESP','SPAIN'),
    ('SWE','SWEDEN'),
    ('CHE','SWITZERLAND'),
    ('TUR','TURKEY'),
    ('GBR','UNITED KINGDOM'),
    ('ZZZ','Other'),
)
